### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by qq634421026** [zhlucky/SaleProgressView#1]
感觉用如背景图片不是圆角的时候，用BitmapShader好像更简单。你可以尝试下

**Comment by Yuan-Programmer** [comment]
好！ 不过内存消耗挺大

**Comment by shengMR** [comment]
onDraw一直new，很是消耗内存

**Comment by zhlucky** [comment]
@qq634421026 用BitmapShader的话，还要将背景图按比例缩放到和背景框一样的大小，不然绘制出来会有问题，好像还更麻烦点。。。

**Comment by zhlucky** [comment]
@xjy312 @440582 造成内存消耗的主要原因就是反复的 createBitmap ，为了演示效果，在绘制进度条的时候，没有对 fgBitmap 做非空判断，实际使用的话加入判断就会好一点。至于绘制文字的时候，不同的进度时需要绘制不同文字，做了非空判断就会出现重叠问题，目前没有想到好的解决办法。还有就是取消动画效果的话就会好很多。
