### ISSUE TITLE
看到文字的绘制有点提议

### ISSUE THREAD

**Issue by LouisShark** [zhlucky/SaleProgressView#2]
其实文字的绘制可以重写   ```java: dispatchDraw()```方法，然后在`super.dispatchDraw(canvas)`的下面来写文字的绘制代码，主要是从View的绘制顺序来入手 ，看起来更加优雅，就不需要使用Xfermode了

**Comment by zhlucky** [comment]
@LouisShark 在 View（不是 ViewGroup） 中重写 dispatchDraw 还是比较少见的吧（本人水平有限，没怎么见过这种写法），而且控制文字变色靠绘制顺序就可以实现吗？你这边如果有思路的话，希望可以指点一下，谢谢。
